version: '3.8'

services:
  go:
    image: golang:1.24
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    ports:
      - "8080:8080"

  lint:
    image: golangci/golangci-lint:v1.64.5
    working_dir: /golangci
    volumes:
      - .cache/:/root/cache
      - .:/golangci
      - ./.golangci.yml:/.golangci.yml
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build

volumes:
 go-mod-cache:
 go-build-cache:
